### PR TITLE
Jkamrx/dashboard filter bug

### LINKED ISSUE #1468: Dashboard Filter Bug
* Specific code commit: 7969dc1ab9d4f7c4af852095e4f32e6554931208 
* Version of the web browser and OS: 49.0.1, 10.11.6 El Capitan
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): 
https://test.stemcellcommons.org/#/

### Steps to reproduce
Please list all the actions and the input data used:

1. Select own data set data set filter (note number returned)
2. Select own and public data set filter (note number returned)
3. Remove public data set filter and leave own selected (note number returned)

### Observed behavior
screen shot 2016-10-13 at 11 54 17 am
screen shot 2016-10-13 at 11 54 35 am
screen shot 2016-10-13 at 11 54 47 am

### Expected behavior
Filters should return consistent and correct data sets

**Other combinations malfunction also. Please test different patterns.**

### LINKED ISSUE #1469: Dashboard Filter & Sorting Bug
* Specific code commit: 7969dc1ab9d4f7c4af852095e4f32e6554931208 
* Version of the web browser and OS: 49.0.1, 10.11.6 El Capitan
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): 
https://test.stemcellcommons.org/#/

Related to #1468 
### Steps to reproduce
Please list all the actions and the input data used:

1.  Select Owner Filter
2. Apply sorting

### Observed behavior
screen shot 2016-10-13 at 12 03 54 pm
screen shot 2016-10-13 at 12 04 12 pm

### Expected behavior
Either filters get deselected or filters remain applies after sorting

### PR DESCRIPTION
**Pull request by jkmarx**
Resolves #1468 and resolves #1469

### CODE REVIEW

File: refinery/ui/source/js/dashboard/controllers/dashboard.js [hunk 1]
```diff
@@ -666,6 +671,7 @@ DashboardCtrl.prototype.checkAnalysesFilterSort = function () {
  * @date    2016-05-09
  */
 DashboardCtrl.prototype.checkDataSetsFilter = function () {
+  console.log('in check data sets filter');
```
Comment (flekschas) [inline refinery/ui/source/js/dashboard/controllers/dashboard.js]: Apart from this every thing looks good :)
