### PR TITLE
Specifically set blob api for safari.

### LINKED ISSUE #1465: tabular meta data file upload failing in Safari 10.0.0
* Specific code commit: fad81a20e6ce1334cde6c3350a1bf89fa4b82a81
* Version of the web browser and OS: Safari 10.0.0 on Mac OS X 10.12
* Environment where the error occurred (Vagrant VM and site conf mode or AWS instance): https://test.stemcellcommons.org

### Steps to reproduce
Please list all the actions and the input data used:

1. Used sample data set (https://test.stemcellcommons.org/static/sample-files/refinery-sample-metadata.tsv)
2. Used default selection on upload page and clicked "Upload Dataset".

### Observed behavior
* Upload failed immediately with 500 server response.

### Expected behavior
* Data gets created.

It appears that this is a problem with Safari 10.0.0. The MIME type for the `POST` request is `text/html` whereas in Safari 9.1.3 the MIME type is `application/json`.

Safari 10.0.0 on Mac OS X 10.12:

screen shot 2016-10-12 at 11 02 54 am

Safari 9.1.3 on Mac OS X 10.11.6:

good-safari

screen shot 2016-10-12 at 11 12 02 am

### PR DESCRIPTION
**Pull request by jkmarx**
Resolves #1465

### CODE REVIEW

File: refinery/ui/source/js/data-set-import/controllers/metadata-table.js [hunk 1]
```diff
@@ -126,9 +126,11 @@ MetadataTableImportCtrl.prototype.renderTable = function () {
       // rejoin rows with new line
       var fileStr = dataArr.join('\r\n');
       /* Create a new file with the modified data and the originial file props.
-      * Safari does not support the File API Constructor.
+      * Safari has issues with the File API Constructor.
       * */
-      if (typeof self.$window.File === 'function') {
+      if (self.$window.navigator.userAgent.indexOf('Safari') > 0) {
```
Comment (jkmarx) [inline refinery/ui/source/js/data-set-import/controllers/metadata-table.js]: Add additional comments about sym and whys.
